const routes: { [key: string]: string } = {
  home: '/',
  following: '/following',
  article: '/article/:id',
  category: '/category',
  categoryDetail: '/category/:id',
  search: '/search',
  bookmark: '/bookmark',
  tagDetail: '/tag/:id',
  requestAuthor: '/request-author',
  changePassword: '/change-password',
  adminHome: '/admin',
  dashboard: '/admin/dashboards/crypto',
  messenger: '/admin/dashboards/messenger',
  //đang làm
  managementArticles: '/admin/management/articles',
  addArticle: '/admin/management/articles/add',
  updateArticle: '/admin/management/articles/edit/:id',
  managementUsers: '/admin/management/users',
  managementAuthors: '/admin/management/authors',
  updateAuthor: '/admin/management/authors/edit/:id',
  managementCategories: '/admin/management/categories',
  addCategory: '/admin/management/categories/add',
  updateCategory: '/admin/management/categories/edit/:id',
  managementTags: '/admin/management/tags',
  addTag: '/admin/management/tags/add',
  updateTag: '/admin/management/tags/edit/:id',
  managementPermissions: '/admin/management/permissions',
  addPermission: '/admin/management/permissions/add',
  updatePermission: '/admin/management/permissions/edit/:id',
  managementBookmarks: '/admin/management/bookmarks',
  managementNotification: '/admin/management/notifications',
  //========================
  profileDetails: '/admin/management/profile/details',
  profileSettings: '/admin/management/profile/settings',
  componentsButtons: '/admin/components/buttons',
  componentModals: '/admin/components/modals',
  componentAccordions: '/admin/components/accordions',
  componentsTabs: '/admin/components/tabs',
  componentsBadges: '/admin/components/badges',
  componentsTooltips: '/admin/components/tooltips',
  componentsAvatars: '/admin/components/avatars',
  componentsCards: '/admin/components/cards',
  componentsForms: '/admin/components/forms',
};

export default routes;
